### ISSUE TITLE
Can not connect to node - no useful data

### ISSUE THREAD

**Issue by mmvphil** [btcontract/lnwallet#118] opened 2019-01-04 07:42 UTC
We try connecting to TINKERTIGER 
02c8ca5511b7646546728dda5788a365564a7916832815b72e5aa75ff60e722256@173.208.150.210:9735
but phone returns: no useful data.

**Comment by btcontract** [comment] 2019-01-04 10:04
When I try to scan a QR created from `02c8ca5511b7646546728dda5788a365564a7916832815b72e5aa75ff60e722256@173.208.150.210:9735` I get "Peer 173.208.150.210:9735 does not support data loss protection" which is a different kind of error. What you describe means that QR code can't be parsed at all.

What's your app version? (can be seen in wallet settings)

**Comment by btcontract** [comment] 2019-02-05 13:00
Closing for now since could not reproduce.

**Closed by btcontract** 2019-02-05 13:00 UTC

**Comment by PWKad** [comment] 2019-02-28 16:58
Hey I can reproduce this - 

Connect to 

moneni which is updated to latest master LND which prevents opening channels which do not support data loss protection.
