### ISSUE TITLE
cannot acquire 524264 bits from a vector that contains 1024 bits

### ISSUE THREAD

**Issue by iljah** [btcontract/lnwallet#103] opened 2018-11-05 07:05 UTC
Debug info from failed LN transfer after I retried it, original also failed after about 10 h but debug info wasn't available anymore:
```
Your wallet
-->
Node ID: 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f, Channel ID: 582279367976550400, Expiry: 144 blocks, Routing fees: 0.010000% of payment sum + baseline 1000 msat
-->
Node ID: 0327049d8d63f0c40193cdf3afc61817c8647808a4e482de0716fcef74e6d92ebf, Channel ID: 586439919927623681, Expiry: 144 blocks, Routing fees: 0.000100% of payment sum + baseline 1000 msat
-->
Node ID: 02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b, Channel ID: 603209671361232897, Expiry: 144 blocks, Routing fees: 0.000100% of payment sum + baseline 0 msat
-->
Payee: 0350494047c6550f575b645cc263b7bf5d7af60a381994eef2896f4d4b4d27229f, Expiry: 10 blocks

Success(ErrorPacket(0327049d8d63f0c40193cdf3afc61817c8647808a4e482de0716fcef74e6d92ebf,TemporaryChannelFailure(ChannelUpdate(3045022100ad1acb7acb29b5a1b726feec5e859fa9a028a195cffdf6a931801670ad441a1e022068d6cd22dcc9ee1c0c0c29d22cdce52f90cd144a1257a7e2c5b2cae547b7cb6201,6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,586439919927623681,1541353730,0,1,144,1000,1000,1,None))))
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
```
Debug info had several ...1024 bits errors but they all seemed similar...

**Comment by btcontract** [comment] 2018-11-05 07:40
> original also failed after about 10 h but debug info wasn't available anymore

That's normal as debug info is currently stored in memory only, it will disappear after app restart.

A `cannot acquire 524264 bits` error itself means that one of nodes along a payment route replied with something which BLW could not even parse, this is probably due to a bug in that remote node.

**Comment by iljah** [comment] 2018-11-05 07:48
Any way to tell which node?

**Comment by btcontract** [comment] 2018-11-05 07:54
No, as that info is contained in a message which should have been parsed. That's exactly one of the problems with current onion design, it's going to be fixed in future versions. Currently BLW just discards every channel in an affected route if it encounters a parsing failure.

**Comment by btcontract** [comment] 2018-11-05 17:42
Closing this as all of this is expected behavior

**Comment by btcontract** [comment] 2019-01-12 09:00
Fixed in https://github.com/lightningnetwork/lnd/pull/2462

**Closed by btcontract** 2019-01-12 09:00 UTC
