### ISSUE TITLE
Channel sleeps forever

### ISSUE THREAD

**Issue by gustavonalle** [btcontract/lnwallet#134] opened 2019-04-05 10:23 UTC
Tried to open a channel on  April 1st, the commitent tx took a while to be confirmed due to low fees chosen and the btc mempool filled right after. Now after 3 days the
 channel is permanently in SLEEPING state.

![img](https://i.ibb.co/sRq9Mxt/Screenshot-20190405-065920.jpg)

**Comment by btcontract** [comment] 2019-04-05 10:42
"online" means socket connection is there but "SLEEPING" means there is no message exchange between nodes. 

It's not yet possible to tell on which end the problem is (but I suspect LND since similar cases happened in past and were resolved by node restart). 

Would be great if https://github.com/PierreRochard could take a look at logs and see whether LND receives and sends a `ChannelReestablish` to your node. BLW node id can be obtained from menu (three dots) on channel details page.

**Comment by gustavonalle** [comment] 2019-04-05 10:59
Hey @PierreRochard, fancy some troubleshooting session? 

My node id is ```03aaed5821cee47c30a4770563b122da666dfc246117627b8f21ba151e81cc42c2```

**Comment by btcontract** [comment] 2019-04-05 12:02
Thanks, just be sure, can you kill a wallet app (not just put it to background), then open again and check if it's still sleeping?

**Comment by gustavonalle** [comment] 2019-04-05 12:16
Killed it, also restarted the phone, still SLEEPING.

**Comment by PierreRochard** [comment] 2019-04-05 15:44
@gustavonalle 
This is what I see on my end

```

        {
            "channel_point": "6fd9a2a94f44808da3ad8871a528b66a0010b217c26a0407455e550ef779a5ab:0",
            "chan_id": "0",
            "chain_hash": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
            "closing_tx_hash": "0000000000000000000000000000000000000000000000000000000000000000",
            "remote_pubkey": "03aaed5821cee47c30a4770563b122da666dfc246117627b8f21ba151e81cc42c2",
            "capacity": "500000",
            "close_height": 0,
            "settled_balance": "0",
            "time_locked_balance": "0",
            "close_type": "FUNDING_CANCELED"
        },
```

**Comment by btcontract** [comment] 2019-04-05 15:51
Interesting, this is something new. Apparently LND decided that remote funding was cancelled despite it having 46+ confirmations by now. So when BLW connects now LND can't find a local channel (since it's closed from it's point of view), that's why BLW dipsplays it as SLEEPING.

Perhaps because it was pending for a 3-4 days? Anyway, that seems like too short a time window, I'll open an issue at LND.

**Comment by btcontract** [comment] 2019-04-05 15:59
@gustavonalle the money is not lost but I'm afraid the only option is local force-close now. Would't advise to do it right away though, maybe this channel can be recovered somehow, let's see what LND team will say.

**Comment by gustavonalle** [comment] 2019-04-05 16:22
Thanks, I will leave it as-is for now 👍

**Comment by btcontract** [comment] 2019-04-05 19:41
Well, looks like force-close it is. LND just dropped a channel because it was taking too long accoring to currentl LND settings.

**Closed by btcontract** 2019-04-05 19:41 UTC
