### ISSUE TITLE
Invoice paid - LBW still displays is as pending

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#55] opened 2018-06-14 06:46 UTC
Latest version of LBW, connected to ACINQ node paying for some pixels in satoshis.place.
In rare cases (happened few times over last 2 weeks) - invoice will be paid (recipient will accept payment) - but app will keep displaying it as in-flight.

Here is latest occurence:
payment hash: 
`d88d9a8b0f64deb8d9b6e31f84ac37a86ff3e8e35687b64dc145ca8bb25d0175`

screen shoot:
![screenshot_20180614-073945](https://user-images.githubusercontent.com/19826327/41395842-0508e20a-6fa7-11e8-8c94-418838fb4c8d.png)

route details:
`-->
Node ID: 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f, channel ID: 579426135262625792, expiry delta: 144 blocks, routing fee: 0.010000% of sum + baseline 1000 msat
-->
Node ID: 03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56, channel ID: 579453623077502977, expiry delta: 144 blocks, routing fee: 0.250000% of sum + baseline 1000 msat
-->
Payee: 024655b768ef40951b20053a5c4b951606d4d86085d51238f2c67c7dec29c792ca, expiry delta: 8`

**Comment by btcontract** [comment] 2018-06-14 07:20
Does it stay that way after app restart or does it become fulfilled?

**Comment by irekzielinski** [comment] 2018-06-14 08:30
Nothing changes after app restart. In the past payment appeared as inflight until channel was closed

**Comment by btcontract** [comment] 2018-06-14 09:05
And what does the "channel view page" say? Is there a "1 payment in-flight" message or "No payments in-flight"? Also, what's the peer you're connected to?

**Comment by irekzielinski** [comment] 2018-06-14 09:16
1 payment in flight

**Comment by btcontract** [comment] 2018-06-14 09:21
OK, it does seem like wallet has not received a payment preimage even though payee has fulfilled it. This is technically possible and means that either some node along the payment route withholds a preimage or we have some kind of wallet bug.

Can you please provide a payment hash and a peer you're connected to? (hopefully it's ACINQ, I'll try to contact owners to check the payment state on their side).

**Comment by irekzielinski** [comment] 2018-06-14 09:29
at work right now so this will have to wait until evening. 

are details i submitted initialy not enough? (there is payment hash, and route details - first hop is acinq node im connected to).

**Comment by btcontract** [comment] 2018-06-14 09:32
Indeed, sorry, too busy with other stuff so missing the obvious. There's enough info already.

**Comment by btcontract** [comment] 2018-06-14 16:52
Turned out a preimage was being witheld by one of routing nodes for some time, it was not ACINQ since they've confirmed they also had your pending payment 7 hours ago. And a few minutes ago yalls owner (next to ACINQ down the route) has confirmed there are no pending payments bu now.

Is the payment resolved in your wallet?

**Comment by irekzielinski** [comment] 2018-06-14 16:56
just started the app: payment appears as "failed and refunded"

**Comment by btcontract** [comment] 2018-06-14 17:07
well there's definitely was a bug somewhere but at least not in BLW. You've got a service rendered and also get the money back but some node along a payment route took a hit by force-closing their channel because of payment expiration.

**Closed by btcontract** 2018-06-14 17:07 UTC
