### ISSUE TITLE
Can't send payment on Tippin.me

### ISSUE THREAD

**Issue by arminbusatlic** [btcontract/lnwallet#113] opened 2018-12-08 23:47 UTC
Hi there. I tried sending 10000 satoshis to a few people on Tippin.me without success. Attached are screenshots and debug info.

Debug:

Your wallet
-->
Node ID: 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f, Channel ID: 592553204595359744, Expiry: 144 blocks, Routing fees: 0.010000% of payment sum + baseline 1000 msat
-->
Node ID: 02a45def9ae014fdd2603dd7033d157faa3a55a72b06a63ae22ef46d9fafdc6e8d, Channel ID: 606370767159361536, Expiry: 144 blocks, Routing fees: 0.010000% of payment sum + baseline 1000 msat
-->
Payee: 03c2abfa93eacec04721c019644584424aab2ba4dff3ac9bdab4e9c97007491dda, Expiry: 154 blocks

Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)
==
Failure(java.lang.IllegalArgumentException: cannot acquire 524264 bits from a vector that contains 1024 bits)

![screenshot_20181208-184137](https://user-images.githubusercontent.com/2653785/49691855-a4a79380-fb19-11e8-92e7-6bc4311b628c.png)
![screenshot_20181208-184143](https://user-images.githubusercontent.com/2653785/49691856-a4a79380-fb19-11e8-84ac-01e8a4765491.png)
![screenshot_20181208-184239](https://user-images.githubusercontent.com/2653785/49691857-a4a79380-fb19-11e8-9edd-8937ee7bb1bf.png)
![screenshot_20181208-184243](https://user-images.githubusercontent.com/2653785/49691858-a4a79380-fb19-11e8-812a-be54a01ec9e4.png)

Any help is greatly appreciated!

Armin

**Comment by btcontract** [comment] 2018-12-09 09:01
This `Failure(java.lang.IllegalArgumentException...` happens when wallet can not decode an onion response from one of peers along the payment route. 

Typically this happens because one of those peers is buggy but BLW itself had an onion-related decoding bug which was fixed a few weeks ago. Judging by screenshots you have a rather outdated app version so it may still have that bug. Can you update an app and try again?

**Comment by arminbusatlic** [comment] 2018-12-09 18:42
Updated the app. Same error. I'm connected to the ACINQ node. Trying now to establish a direct channel with Tippin to see if that helps.

**Comment by arminbusatlic** [comment] 2018-12-09 23:19
I opened a channel directly with Tippin. Worked flawlessly. Was able to send 20 different lightning payments in seconds.

Definitely something wrong with the Acinq node.

**Comment by btcontract** [comment] 2018-12-10 05:11
This is strange as they're the last node is think on. I'll investigate this asap.

**Comment by btcontract** [comment] 2018-12-12 06:00
Could not reproduce with ACINQ channel so closing this for now.

**Comment by yilmzfurkan** [comment] 2018-12-12 07:54
Can confirm that when the issue opened I had the same problem but just tried now it went through. Probably the channel between ACINQ-tippin.me had closed somehow.

**Comment by btcontract** [comment] 2019-01-12 09:00
Fixed in https://github.com/lightningnetwork/lnd/pull/2462

**Closed by btcontract** 2019-01-12 09:00 UTC
